name: Check for broken links

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-mail
            **/*.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
